// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuTS8xLF617vmMbxKfjxKy5ivEcntz5o0',
    appId: '1:417521024759:web:73d7d041f44433b4ac1df2',
    messagingSenderId: '417521024759',
    projectId: 'loginsimpleex',
    authDomain: 'loginsimpleex.firebaseapp.com',
    storageBucket: 'loginsimpleex.appspot.com',
    measurementId: 'G-BR8HEXX7Q7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdCBaQIM3cOveZi5_PMssuIsWSqUBYyQc',
    appId: '1:417521024759:android:4736fccb0c60fe1cac1df2',
    messagingSenderId: '417521024759',
    projectId: 'loginsimpleex',
    storageBucket: 'loginsimpleex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_1u26RQBkc2S6wKaFXC_n5RfqwA7UDbs',
    appId: '1:417521024759:ios:264e91fed7ec8e9aac1df2',
    messagingSenderId: '417521024759',
    projectId: 'loginsimpleex',
    storageBucket: 'loginsimpleex.appspot.com',
    iosBundleId: 'com.example.flutter1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_1u26RQBkc2S6wKaFXC_n5RfqwA7UDbs',
    appId: '1:417521024759:ios:03d2dc95afdd0666ac1df2',
    messagingSenderId: '417521024759',
    projectId: 'loginsimpleex',
    storageBucket: 'loginsimpleex.appspot.com',
    iosBundleId: 'com.example.flutter1.RunnerTests',
  );
}
